class FoodItem {
  final String id;
  final String name;
  final String description;
  final double price;
  final String imageUrl;
  final String category;
  final double rating;
  final String prepTime;
  final bool isVeg;

  FoodItem({
    required this.id,
    required this.name,
    required this.description,
    required this.price,
    required this.imageUrl,
    required this.category,
    required this.rating,
    required this.prepTime,
    required this.isVeg,
  });
}

class MockData {
  static final List<String> categories = [
    'Starters',
    'Biryani',
    'Main Course',
    'Rolls',
    'Chinese',
    'Beverages',
    'Desserts',
    'Cakes',
    'Ice Creams'
  ];

  static final List<FoodItem> foodItems = [
    // Starters
    FoodItem(
      id: '1',
      name: 'Chicken 65',
      description: 'Spicy, deep-fried chicken pieces with curry leaves and green chilies.',
      price: 220.0,
      imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=800&auto=format&fit=crop',
      category: 'Starters',
      rating: 4.7,
      prepTime: '15 min',
      isVeg: false,
    ),
    FoodItem(
      id: 's2',
      name: 'Paneer Tikka',
      description: 'Marinated paneer chunks grilled to perfection.',
      price: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1599487405270-86430a634392?q=80&w=800&auto=format&fit=crop',
      category: 'Starters',
      rating: 4.5,
      prepTime: '15 min',
      isVeg: true,
    ),
    FoodItem(
      id: 's3',
      name: 'Chilli Chicken',
      description: 'Sweet, spicy & slightly sour crispy appetizer.',
      price: 240.0,
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
      category: 'Starters',
      rating: 4.6,
      prepTime: '20 min',
      isVeg: false,
    ),
    
    FoodItem(
      id: 's4',
      name: 'Gobi Manchurian',
      description: 'Crispy cauliflower florets tossed in a spicy, sweet, and tangy sauce.',
      price: 160.0,
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop',
      category: 'Starters',
      rating: 4.4,
      prepTime: '20 min',
      isVeg: true,
    ),
    FoodItem(
      id: 's5',
      name: 'Crispy Corn',
      description: 'Fried sweet corn kernels tossed with spices.',
      price: 140.0,
      imageUrl: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?q=80&w=800&auto=format&fit=crop',
      category: 'Starters',
      rating: 4.3,
      prepTime: '10 min',
      isVeg: true,
    ),
    FoodItem(
      id: 's6',
      name: 'Spring Rolls',
      description: 'Crispy fried rolls stuffed with fresh julienned vegetables.',
      price: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1596450514735-111a2fe02935?q=80&w=800&auto=format&fit=crop',
      category: 'Starters',
      rating: 4.5,
      prepTime: '15 min',
      isVeg: true,
    ),
    
    // Biryani
    FoodItem(
      id: 'b1',
      name: 'Special Chicken Biryani',
      description: 'Slow-cooked aromatic basmati rice with tender chicken and authentic spices.',
      price: 350.0,
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?q=80&w=800&auto=format&fit=crop',
      category: 'Biryani',
      rating: 4.8,
      prepTime: '25 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'b2',
      name: 'Mutton Dum Biryani',
      description: 'Classic dum biryani cooked with succulent mutton pieces.',
      price: 450.0,
      imageUrl: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=800&auto=format&fit=crop',
      category: 'Biryani',
      rating: 4.9,
      prepTime: '30 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'b3',
      name: 'Veg Dum Biryani',
      description: 'Fragrant basmati rice mixed with fresh vegetables and spices.',
      price: 280.0,
      imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
      category: 'Biryani',
      rating: 4.4,
      prepTime: '20 min',
      isVeg: true,
    ),

    FoodItem(
      id: 'b4',
      name: 'Egg Biryani',
      description: 'Aromatic basmati rice cooked with boiled eggs and special spices.',
      price: 220.0,
      imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
      category: 'Biryani',
      rating: 4.2,
      prepTime: '20 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'b5',
      name: 'Paneer Biryani',
      description: 'Delicious vegetarian biryani made with soft paneer cubes.',
      price: 260.0,
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop',
      category: 'Biryani',
      rating: 4.5,
      prepTime: '25 min',
      isVeg: true,
    ),
    FoodItem(
      id: 'b6',
      name: 'Prawns Biryani',
      description: 'Rich and flavorful biryani cooked with fresh juicy prawns.',
      price: 420.0,
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?q=80&w=800&auto=format&fit=crop',
      category: 'Biryani',
      rating: 4.7,
      prepTime: '30 min',
      isVeg: false,
    ),

    // Rolls
    FoodItem(
      id: 'r1',
      name: 'Chicken Tikka Roll',
      description: 'Spicy chicken tikka wrapped in a flaky paratha.',
      price: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1626804475297-41609ea004eb?q=80&w=800&auto=format&fit=crop',
      category: 'Rolls',
      rating: 4.5,
      prepTime: '15 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'r2',
      name: 'Paneer Roll',
      description: 'Grilled paneer wrapped with onions and mint chutney.',
      price: 120.0,
      imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=800&auto=format&fit=crop',
      category: 'Rolls',
      rating: 4.4,
      prepTime: '10 min',
      isVeg: true,
    ),

    // Chinese
    FoodItem(
      id: 'c1',
      name: 'Veg Manchurian',
      description: 'Fried vegetable balls in a spicy, sweet, and tangy sauce.',
      price: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop', // Same image as dal for placeholder
      category: 'Chinese',
      rating: 4.6,
      prepTime: '20 min',
      isVeg: true,
    ),

    // Main Course
    FoodItem(
      id: 'm1',
      name: 'Paneer Butter Masala',
      description: 'Rich and creamy tomato-based gravy with soft paneer cubes.',
      price: 280.0,
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop',
      category: 'Main Course',
      rating: 4.5,
      prepTime: '20 min',
      isVeg: true,
    ),
    FoodItem(
      id: 'm2',
      name: 'Butter Chicken',
      description: 'Tender chicken pieces in a mild, creamy tomato curry.',
      price: 320.0,
      imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=800&auto=format&fit=crop',
      category: 'Main Course',
      rating: 4.8,
      prepTime: '25 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'm3',
      name: 'Mutton Haleem',
      description: 'Slow-cooked stew of meat, lentils, and pounded wheat.',
      price: 350.0,
      imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=800&auto=format&fit=crop',
      category: 'Main Course',
      rating: 4.9,
      prepTime: '30 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'm4',
      name: 'Dal Makhani',
      description: 'Creamy black lentils slow-cooked to perfection.',
      price: 220.0,
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop',
      category: 'Main Course',
      rating: 4.6,
      prepTime: '20 min',
      isVeg: true,
    ),

    FoodItem(
      id: 'm5',
      name: 'Kadai Paneer',
      description: 'Paneer and bell peppers cooked in a spicy masala.',
      price: 260.0,
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop',
      category: 'Main Course',
      rating: 4.5,
      prepTime: '20 min',
      isVeg: true,
    ),
    FoodItem(
      id: 'm6',
      name: 'Chicken Tikka Masala',
      description: 'Roasted marinated chicken chunks in a spiced sauce.',
      price: 340.0,
      imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=800&auto=format&fit=crop',
      category: 'Main Course',
      rating: 4.8,
      prepTime: '25 min',
      isVeg: false,
    ),

    // Beverages
    FoodItem(
      id: 'v1',
      name: 'Mango Lassi',
      description: 'Sweet and creamy yogurt-based mango drink.',
      price: 90.0,
      imageUrl: 'https://images.unsplash.com/photo-1546889504-06c3a50e50e9?q=80&w=800&auto=format&fit=crop',
      category: 'Beverages',
      rating: 4.7,
      prepTime: '5 min',
      isVeg: true,
    ),
    FoodItem(
      id: 'v2',
      name: 'Masala Chai',
      description: 'Classic Indian spiced tea.',
      price: 40.0,
      imageUrl: 'https://images.unsplash.com/photo-1576092762791-dd9e2220afa1?q=80&w=800&auto=format&fit=crop',
      category: 'Beverages',
      rating: 4.5,
      prepTime: '10 min',
      isVeg: true,
    ),

    // Desserts
    FoodItem(
      id: 'd1',
      name: 'Gulab Jamun',
      description: 'Soft milk solids dumplings dipped in cardamom-flavored sugar syrup.',
      price: 120.0,
      imageUrl: 'https://images.unsplash.com/photo-1589119908995-c6837fa14848?q=80&w=800&auto=format&fit=crop',
      category: 'Desserts',
      rating: 4.9,
      prepTime: '10 min',
      isVeg: true,
    ),
    FoodItem(
      id: 'd2',
      name: 'Rasmalai',
      description: 'Soft paneer discs soaked in sweet, thickened milk.',
      price: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1668231267866-6b22c2a05f03?q=80&w=800&auto=format&fit=crop',
      category: 'Desserts',
      rating: 4.8,
      prepTime: '10 min',
      isVeg: true,
    ),

    // Cakes
    FoodItem(
      id: 'ck1',
      name: 'Chocolate Truffle Cake',
      description: 'Rich chocolate cake with dense truffle ganache.',
      price: 450.0,
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800&auto=format&fit=crop',
      category: 'Cakes',
      rating: 4.9,
      prepTime: '20 min',
      isVeg: false,
    ),
    FoodItem(
      id: 'ck2',
      name: 'Red Velvet Cake',
      description: 'Classic red velvet cake with cream cheese frosting.',
      price: 550.0,
      imageUrl: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?q=80&w=800&auto=format&fit=crop',
      category: 'Cakes',
      rating: 4.7,
      prepTime: '20 min',
      isVeg: false,
    ),

    // Ice Creams
    FoodItem(
      id: 'ic1',
      name: 'Vanilla Bean Ice Cream',
      description: 'Classic creamy vanilla ice cream made with real beans.',
      price: 120.0,
      imageUrl: 'https://images.unsplash.com/photo-1570197781417-0c7a5270f2c8?q=80&w=800&auto=format&fit=crop',
      category: 'Ice Creams',
      rating: 4.6,
      prepTime: '5 min',
      isVeg: true,
    ),
    FoodItem(
      id: 'ic2',
      name: 'Chocolate Fudge Brownie',
      description: 'Decadent chocolate ice cream loaded with brownie chunks.',
      price: 160.0,
      imageUrl: 'https://images.unsplash.com/photo-1557142046-c704a3adf364?q=80&w=800&auto=format&fit=crop',
      category: 'Ice Creams',
      rating: 4.8,
      prepTime: '5 min',
      isVeg: true,
    ),
  ];
}
